version: '3'

networks:
  default:
    name: lamassu-iot-network
    external: true

volumes:
  azure_data:
  aws_data:

services:
  azure-connector:
    container_name: azure-connector
    build: 
      context: ../lamassu/lamassu-azure/azure-connector
      args: 
        BASE_IMAGE: alpine:3.14
    environment:
      SERVICE_NAME: azure-connector
      DEBUG_MODE: "true"
      PORT: 8011
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces
      DEVICE_MANAGER_ADDRESS: device-manager:8085
      LAMASSU_CA_ADDRESS: ca:8085
      LAMASSU_CA_CERT_FILE: /certs/internal-ca.crt
      CONNECTOR_TYPE: azure
      CONNECTOR_NAME: "Azure Ikerlan Account"
      CONNECTOR_PERSISTENCE_DIR: /app/pv
      CONSUL_PROTOCOL: https
      CONSUL_HOST: consul-server
      CONSUL_PORT: 8501
      CONSUL_CA: /certs/internal-ca.crt
      AZURE_SUBSCRIPTION_ID: "eb15290f-a86e-499e-97a2-faac9a2a5a73"
      AZURE_TENANT_ID: "e6c819e2-a186-4ed2-a29b-0172c300bc25"
      AZURE_CLIENT_ID: "697420cf-059a-4b07-8d5c-74acb833c869"
      AZURE_CLIENT_SECRET: "sII8Q~Ql2_.f345uFAUGkkWJMgBQEQKQhmaEHa.t"
      AZURE_DPS_SAS_TOKEN_KEY: "lh71Oy+tEzIaM3opem3s76RwM3+wbNScb73I8wrgvp0="
      AZURE_HUB_SAS_TOKEN_KEY: "q6UiV9K/yPqfZ1c9IcvpJUzduS7TMTetoY4NJftQAu4="
      AZURE_RESOURCE_GROUP: lamassu-rg
      AZURE_DPS_NAME: lamassu-dps
    volumes:
      - azure_data:/app/pv
      - ./tls-certificates/upstream/azure-connector/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/azure-connector/tls.key:/certs/tls.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure

  aws-connector:
    container_name: aws-connector
    build: 
      context: ../lamassu/lamassu-aws/aws-connector
      args: 
        BASE_IMAGE: alpine:3.14
    environment:
      SERVICE_NAME: azure-connector
      DEBUG_MODE: "true"
      PORT: 8011
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces

      LAMASSU_CA_ADDRESS: ca:8087
      LAMASSU_CA_CERT_FILE: /certs/internal-ca.crt
      CONNECTOR_TYPE: aws
      CONNECTOR_NAME: "AWS Ikerlan Account"
      CONNECTOR_PERSISTENCE_DIR: /app/pv
      CONSUL_PROTOCOL: https
      CONSUL_HOST: consul-server
      CONSUL_PORT: 8501
      CONSUL_CA: /certs/internal-ca.crt
      AWS_ACCESS_KEY_ID: AKIAVBB6ZXAOGZHRMQ6T
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: eu-west-1
      AWS_SQS_INBOUND_QUEUE_NAME: lamassuResponse
    volumes:
      - aws_data:/app/pv
      - ./tls-certificates/upstream/aws-connector/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/aws-connector/tls.key:/certs/tls.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure