version: '3'

networks:
  default:
    name: lamassu-iot-network
    external: true

volumes:
  consul_server_data:
  postgres_data:
  jaeger_tracing_data:

services:
  api-gateway:
    image: ${LAMASSU_GATEWAY_DOCKER_IMAGE}
    container_name: api-gateway 
    environment:
      DOMAIN: ${DOMAIN}
      DEBUG_MODE: ${DEBUG_MODE}
    ports:
      - 80:80
      - 443:443
      - 9900:9900
    volumes:
      - ./tls-certificates/downstream/tls.crt:/certs/downstream.crt:ro
      - ./tls-certificates/downstream/tls.key:/certs/downstream.key:ro
      - ./tls-certificates/downstream/tls.crt:/certs/downstream-ca.crt:ro
      - ./tls-certificates/upstream/api-gateway/tls.crt:/certs/upstream.crt:ro 
      - ./tls-certificates/upstream/api-gateway/tls.key:/certs/upstream.key:ro
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt:ro
    depends_on:
      - jaeger
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}
      
  database:
    image: ${LAMASSU_DB_DOCKER_IMAGE}
    container_name: database
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  opa-server:
    image: openpolicyagent/opa:0.37.1-envoy
    container_name: opa-server
    volumes:
      - ./config/opa/policy.rego:/opa/policy.rego
      - ./config/opa/config.yaml:/opa/config.yaml
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--config-file=/opa/config.yaml"
      - "--log-level=info"
      - "--log-format=text"
      - "--ignore=.*"
      - "/opa/policy.rego"
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  jaeger:
    image: jaegertracing/all-in-one:1.30.0
    container_name: jaeger
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: /badger/data
    volumes:
      - jaeger_tracing_data:/badger
    # ports:
    #   - 14268:14268
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  ui:
    image: ${LAMASSU_UI_DOCKER_IMAGE}
    container_name: lamassu-ui
    environment:
      DOMAIN: ${DOMAIN}
      REACT_APP_AUTH_ENDPOINT: "https://auth.${DOMAIN}/auth"
      REACT_APP_AUTH_REALM: "lamassu"
      REACT_APP_AUTH_CLIENT_ID: "frontend"
      REACT_APP_LAMASSU_CLOUD_PROXY_API: "https://${DOMAIN}:8081"
      REACT_APP_LAMASSU_CA_API: "https://${DOMAIN}/api/ca"
      REACT_APP_LAMASSU_DMS_MANAGER_API: "https://${DOMAIN}/api/dmsmanager"
      REACT_APP_LAMASSU_DEVMANAGER: "https://${DOMAIN}/api/devmanager"
    volumes: 
      - ./tls-certificates/upstream/ui/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/ui/tls.key:/certs/tls.key
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  consul-server:
    image: consul:1.9
    container_name: consul
    # ports:
    #   - 8500:8500
    #   - 8501:8501
    volumes:
      - consul_server_data:/consul/data
      - ./config/consul/config.json:/consul/config/server.json
      - ./tls-certificates/upstream/ca.crt:/consul/tls/internal-ca.crt
      - ./tls-certificates/upstream/consul-server/tls.crt:/consul/tls/tls.crt
      - ./tls-certificates/upstream/consul-server/tls.key:/consul/tls/tls.key
    command: consul agent -server -bootstrap-expect=1 -data-dir /consul/data -config-dir /consul/config
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  vault:
    image: vault:1.7.3
    container_name: vault
    volumes:
      - ./config/vault/config.json:/vault/config/config.json
      - ./tls-certificates/upstream/consul-server/tls.crt:/vault/tls/consul.crt
      - ./tls-certificates/upstream/vault/tls.crt:/vault/tls/tls.crt
      - ./tls-certificates/upstream/vault/tls.key:/vault/tls/tls.key
    command: vault server -config /vault/config/config.json
    cap_add:
      - IPC_LOCK
    depends_on: 
      - consul-server
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  auth:
    image: ${LAMASSU_AUTH_DOCKER_IMAGE}
    container_name: auth
    environment:
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_DATABASE: auth
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/lamassu.json
    volumes:
      - ./tls-certificates/upstream/auth/tls.crt:/etc/x509/https/tls.crt
      - ./tls-certificates/upstream/auth/tls.key:/etc/x509/https/tls.key
      - ./config/auth/lamassu.v2:/opt/jboss/keycloak/themes/lamassu.v2
    depends_on:
      - database
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  ca:
    image: ${LAMASSU_CA_DOCKER_IMAGE}
    container_name: ca
    environment:
      SERVICE_NAME: ca
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: 8085
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces
      OCSP_URL: https://${DOMAIN}/api/ocsp/
      VAULT_ADDRESS: https://vault:8200
      VAULT_ROLE_ID: ${CA_VAULT_ROLE_ID}
      VAULT_SECRET_ID: ${CA_VAULT_SECRET_ID}
      VAULT_CA: /certs/vault.crt
      VAULT_PKI_CA_PATH: pki/lamassu/dev/
      VAULT_UNSEAL_KEYS_FILE: /config/vault-credentials.json
      POSTGRES_HOSTNAME: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ca
      POSTGRES_USERNAME: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      ENGINE: vault
    volumes:
      - ./tls-certificates/upstream/vault/tls.crt:/certs/vault.crt
      - ./tls-certificates/upstream/ca/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/ca/tls.key:/certs/tls.key
      - ./vault-ca-credentials.json:/config/vault-credentials.json
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}
  
  dms-manager:
    image: ${LAMASSU_DMS_MANAGER_DOCKER_IMAGE}
    container_name: dms-manager
    environment:
      SERVICE_NAME: dms-manager
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: 8085
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces
      POSTGRES_DATABASE: dmsmanager
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOSTNAME: database
      POSTGRES_PORT: 5432
      LAMASSU_CA_ADDRESS: ca:8085
      LAMASSU_CA_CERT_FILE: /certs/internal-ca.crt
    volumes:
      - ./tls-certificates/upstream/dms-manager/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/dms-manager/tls.key:/certs/tls.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  device-manager:
    container_name: device-manager
    image: ${LAMASSU_DEVICE_MANAGER_DOCKER_IMAGE}
    environment: 
      SERVICE_NAME: device-manager
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: 8085
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces
      POSTGRES_HOSTNAME: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: devicemanager
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      MINIMUM_REENROLL_DAYS: ${DEVICE_MANAGER_MINIMUM_REENROLL_DAYS}
      LAMASSU_CA_ADDRESS: ca:8085
      LAMASSU_CA_CERT_FILE: /certs/internal-ca.crt
      LAMASSU_DMS_MANAGER_ADDRESS: dms-manager:8085
      LAMASSU_DMS_MANAGER_CERT_FILE: /certs/internal-ca.crt
    volumes:
      - ./tls-certificates/upstream/device-manager/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/device-manager/tls.key:/certs/tls.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  ocsp:
    container_name: ocsp
    image: ${LAMASSU_OCSP_DOCKER_IMAGE}
    environment:
      SERVICE_NAME: ocsp
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: 8085
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces
      LAMASSU_CA_ADDRESS: ca:8085
      LAMASSU_CA_CERT_FILE: /certs/internal-ca.crt
      SIGNER_CERT: /certs/signer.crt
      SIGNER_KEY: /certs/signer.key
    volumes:
      - ./tls-certificates/upstream/ocsp/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/ocsp/tls.key:/certs/tls.key
      - ./tls-certificates/downstream/tls.crt:/certs/signer.crt
      - ./tls-certificates/downstream/tls.key:/certs/signer.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  alerts:
    image: ${LAMASSU_ALERTS_DOCKER_IMAGE}
    container_name: alerts
    environment:
      SERVICE_NAME: alerts
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: 8085
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: alerts
      POSTGRES_HOSTNAME: database
      POSTGRES_PORT: 5432
      SMTP_FROM: lamassu-alerts@ikerlan.es
      SMTP_INSECURE: "true"
      SMTP_ENABLE_SSL: "true"
      SMTP_USERNAME: "" 
      SMTP_PASSWORD: ""
      SMTP_HOST: "172.16.255.146"
      SMTP_PORT: 25
      TEMPLATE_HTML: /app/templates/email.html
      TEMPLATE_JSON: /app/templates/config.json
    volumes:
      - ./tls-certificates/upstream/alerts/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/alerts/tls.key:/certs/tls.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  cloud-proxy:
    image: ${LAMASSU_CLOUD_PROXY_DOCKER_IMAGE}
    container_name: cloud-proxy
    environment:
      SERVICE_NAME: cloud-proxy
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: 8085
      PROTOCOL: https
      CERT_FILE: /certs/tls.crt
      KEY_FILE: /certs/tls.key
      MUTUAL_TLS_ENABLED: "true"
      MUTUAL_TLS_CLIENT_CA: /certs/internal-ca.crt
      AMQP_SERVER_ENABLE_TLS: "true"
      AMQP_SERVER_HOST: rabbitmq      
      AMQP_SERVER_PORT: 5671
      AMQP_SERVER_CA_CERT: /certs/internal-ca.crt
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
      JAEGER_EXPORTER_URL: http://jaeger:14268/api/traces
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: cloudproxy
      POSTGRES_HOSTNAME: database
      POSTGRES_PORT: 5432
      CONSUL_PROTOCOL: https
      CONSUL_HOST: consul-server
      CONSUL_PORT: 8501
      CONSUL_CA: /certs/internal-ca.crt
      LAMASSU_CA_ADDRESS: ca:8085
      LAMASSU_CA_CERT_FILE: /certs/internal-ca.crt
      LAMASSU_CONNECTORS_MUTUAL_TLS: "true"
      LAMASSU_CONNECTORS_CERT_FILE: /certs/internal-ca.crt
    volumes:
      - ./tls-certificates/upstream/cloud-proxy/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/cloud-proxy/tls.key:/certs/tls.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}

  rabbitmq:
    image: ${LAMASSU_RABBITMQ_DOCKER_IMAGE}
    container_name: rabbitmq
    # ports:
    #    - 5671:5671
    #    - 5672:5672
    #    - 15672:15672
    #    - 15671:15671
    volumes:
      - ./tls-certificates/upstream/rabbitmq/tls.crt:/certs/tls.crt
      - ./tls-certificates/upstream/rabbitmq/tls.key:/certs/tls.key
      - ./tls-certificates/upstream/ca.crt:/certs/internal-ca.crt
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    logging:
      driver: "json-file"
      options:
        max-file: ${MAX_LOG_FILES}
        max-size: ${MAX_LOG_FILE_SIZE}