name: Main Workflow

on:
  push:
    paths:
      - .github/workflows/develop.yml**
      - config/auth/**
      - config/envoy/**
      - config/rabbitmq/**
    branches:
      - develop
      
jobs:
  build_auxiliar_compose_release:
    name: Build Auxilar Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build lamassu-gateway Docker image
        uses: docker/build-push-action@v2
        with:
          context: config/envoy
          push: true
          tags: |
            lamassuiot/lamassu-gateway-dev:${{ github.sha }}
            lamassuiot/lamassu-gateway-dev:latest
      
      - name: Build lamassu-auth Docker image
        uses: docker/build-push-action@v2
        with:
          context: config/auth
          push: true
          tags: |
            lamassuiot/lamassu-auth-dev:${{ github.sha }}
            lamassuiot/lamassu-auth-dev:latest

      - name: Build lamassu-rabbitmq Docker image
        uses: docker/build-push-action@v2
        with:
          context: config/rabbitmq
          push: true
          tags: |
            lamassuiot/lamassu-rabbitmq-dev:${{ github.sha }}
            lamassuiot/lamassu-rabbitmq-dev:latest